version: "3.8"
services:
  partus_users:
    container_name: partus_users
    build:
      context: ./Partus_users
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - mongo
      - mongo-express
    env_file:
      - ./Partus_users/.env.development
    environment:
      - IN_CONTAINER=true
      - SSL_CERT_FILE=/app/ssl/cert.pem
      - SSL_KEY_FILE=/app/ssl/key.pem
      - SERVER_PORT=50051
    networks:
      - partus_users

  mongo:
    image: mongo
    container_name: mongo_partus_users
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - partus_users:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=partus_users_dev
    networks:
      - partus_users

  mongo-express:
    image: mongo-express
    container_name: me_partus_users
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongo
    volumes:
      - partus_users:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    networks:
      - partus_users

networks:
  partus_users:
    driver: bridge

volumes:
  partus_users:
    external: true
